spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.24.78.196/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
server:
  port: 8081

