#DUBBO
dubbox:
  application:
    name: zhongmc-blog-web-protal
    organization: zmc
    owner: zmc
  registry:
    protocol: zookeeper
    address: 192.168.154.130:2181
  annotation:
    package: com.zhongmc.blog.controller
  monitor:
    enabled: false
    address: 192.168.125.1:6060
    username: admin
    password: admin

#spring:
#  mvc:
#    view:
#      prefix: /templates/
#      suffix: .html
#  freemarker:
#    cache: false
#    request-context-attribute: request

#配置模板想到classpath路径，后面须加上"/"

server:
  port: 8100
spring:
  thymeleaf:
    mode: LEGACYHTML5



